Feat/settings e2e tests
cytechmobile/radicle-vscode-extension pull request #167
Opened 2024-12-01 16:39 UTC by QZera

2025-01-07 20:25 UTC, maninak approved these changes
Well done, zac, and thank you!

2025-01-07 20:27 UTC, maninak requested changes
.

2025-01-08 02:35 UTC, maninak requested changes
I still need to have a second look, particularly for the details of the logic in `settings.spec.ts`, but for now some early comments.

On top of the inline ones, I want to address a couple more general ones:

1. regarding changing setting values, I wonder if we take into account (and if we should, if not) the debounce that seems to be between setting changing the input field's value and it "registering". Perhaps we could "blur" the focus instead of waiting which seems to trigger registering of the new value instantly.
1. if running (a subset, as previously discussed) of the e2e tests locally is now safe, i.e. won't impact local setup, we should revisit restoring the npm script `test:e2e` inside the top-level script "test".

2025-01-08 02:35 UTC, maninak commented on test/e2e/wdio.conf.ts
> +  waitforTimeout: 20000,
What prompted this increase? Is it possible to apply it per case as needed instead?

2025-01-08 02:35 UTC, maninak commented on test/e2e/wdio.conf.ts
> +  ],
I roughly sketched this for you to consider if we could/should use in order to have a single point of definition for those specs that need to be in specific order and also help not forget to keep those array entries in sync as specs get added/removed.

```ts
/**
 * Add to this list any paths to spec files requiring to run in a specific order.
 */
const orderedSpecPaths = ['./specs/onboarding.spec.ts', './specs/settings.spec.ts']

const specsToExcludeFromGlob = orderedSpecPaths
  .map(specPath => specPath.split('/').pop()?.replace('.spec.ts', ''))

;[
  orderedSpecPaths,
  `./specs/**/!(${specsToExcludeFromGlob.join('|')}).spec.ts`,
]
```

Feel free to adjust as needed or outright skip if you think it would be best to keep it WET (instead of DRY but more engineered and restrictive).

**Either way please ensure that we're using** (here and everywhere else as needed) **the OS-agnostic nodejs separator** imported from `node:path`, so that our code is more likely to run on windows (or at worst have less tech debt when the need comes to officially support it).

2025-01-08 02:35 UTC, maninak commented on test/e2e/specs/settings.spec.ts
> +    it.skip('recognizes if the directory is created *after* the setting is updated', async () => {
```suggestion
    it.skip('recognizes if the directory is created *after* the setting is set', async () => {
```

Minor copy improvement. At least for my brain, makes the case description a tad easier to parse.

2025-01-08 02:35 UTC, maninak commented on test/e2e/specs/settings.spec.ts
> +    it.skip('recognizes if the directory is created *after* the setting is updated', async () => {
```suggestion
    it.skip('recognizes if the directory is created *after* the setting is set', async () => {
```

Minor copy improvement. At least for my brain, makes the case description a tad easier to parse.

2025-01-08 02:35 UTC, maninak commented on test/e2e/helpers/assertions.ts
> + * Asserts the output view contains the expected text.
The idiomatic term for this piece of UI is ["Output Panel"](https://code.visualstudio.com/api/extension-capabilities/common-capabilities#output-channel). Best to use that term since the term View is semantically overloaded in the context of VS Code extension development and refers to a specific different entity, which may be misleading.

Myself, I often opt to use Title Case whenever I refer to such idiomatic terms to better hint at that attribute of theirs, though I mindfully often opt not to, when I'm trying to avoid unnecessary visual overload. It's a subtle thing, do as you prefer, just thought I'd mention it once. When in doubt it's better to not use any special casing as using it wrongly would actually make things worse.

2025-01-08 02:35 UTC, maninak commented on test/e2e/helpers/assertions.ts
> +       * The text in the output console is split by newlines, which can be affected by the size
Similarly to previous comment, Console (Panel) is another different piece of UI. Best here to use the term Output Panel or Output Channel (depending on if you prefer pointing to the representational or the model part of the UX (semantics can get complex, I know)).

2025-01-08 02:35 UTC, maninak commented on test/e2e/specs/settings.spec.ts
> +      )
Is it possible to refer to each setting by its identifier instead? It would make for less brittle referencing. Ids are defined in package.json, e.g. here it would be `radicle.advanced.pathToRadBinary`.

![image](https://github.com/user-attachments/assets/74d0acd3-e1bb-4477-b648-1dcf38aea46b)

If you use the above in the settings search you'll get the single expected result
![image](https://github.com/user-attachments/assets/f06cd8fd-7759-4431-b03d-1131a91ce5e4)

If you'd want to go all in you could even search for `@id:radicle.advanced.pathToRadBinary`, but I fail to see how prepending the `@id` makes any material difference. 

Same for all instances of this.

2025-01-08 02:35 UTC, maninak commented on test/e2e/specs/settings.spec.ts
> +    // This functionality does not seem to work
When you find bugs while testing (which is great!!), it's best to create an issue instead, list the repro steps in there which by definition you know, and use a better comment here like e.g.:

```suggestion
    // TODO: unskip when bug #xyz covered by this case is fixed
```

2025-01-08 02:35 UTC, maninak commented on test/e2e/specs/settings.spec.ts
> +  describe('VS Code, when updating the "Path to Radicle to Node Home" setting, @skipLinuxCI', () => {
Skipping tests, especially on Linux CI, along with the whole setup that comes to support this on the runner level is both hacky and and risky.

These various odd issues we've been having on the environment level smell to me that we need to look upwards to sniff out the root cause (e.g. in e2e-testing.yaml, or wdio config, or investigate CLI bug with the maintainers, ...?) or it will keep forcing more hacks down our throats.

At the very least, here could we at least source the value of `RAD_HOME` alternatively e.g. with `rad self --home` and remove all those `@skipLinuxCI` markers and related supporting logic?

2025-01-26 10:45 UTC, QZera commented on test/e2e/wdio.conf.ts
> +  waitforTimeout: 20000,
I increased the timeout because "wait for" statements were inconsistently timing out.

I don't really see any reason not to increase it globally. The timeouts were failing due to vscode itself, not the performance of the extension. And I can't really think of a case where we would want the tests to fail because of that, since it's out of our control.

2025-01-26 10:45 UTC, QZera commented on test/e2e/helpers/assertions.ts
> + * Asserts the output view contains the expected text.
Opted to use Title Case here.

2025-01-26 10:45 UTC, QZera commented on test/e2e/helpers/assertions.ts
> +       * The text in the output console is split by newlines, which can be affected by the size
Went for Output Panel for consistency.

2025-01-26 10:45 UTC, QZera commented on test/e2e/specs/settings.spec.ts
> +      )
Not unless I implement a custom `findSetting`. Here's how vscode-service's `findSetting` fills the search box:

```typescript
    async findSetting (title: string, ...categories: string[]): Promise<Setting> {
        const category = categories.join(' › ')
        await searchBox.setValue(`${category}: ${title}`)
        ...
```

2025-01-26 10:45 UTC, QZera commented on test/e2e/specs/settings.spec.ts
> +    it.skip('recognizes if the directory is created *after* the setting is updated', async () => {
Done!

2025-01-26 10:45 UTC, QZera commented on test/e2e/specs/settings.spec.ts
> +    it.skip('recognizes if the directory is created *after* the setting is updated', async () => {
Done!

2025-01-26 10:45 UTC, QZera commented on test/e2e/specs/settings.spec.ts
> +    // This functionality does not seem to work
Done!

2025-01-26 10:45 UTC, QZera commented on test/e2e/specs/settings.spec.ts
> +  describe('VS Code, when updating the "Path to Radicle to Node Home" setting, @skipLinuxCI', () => {
I believe this might actually be a bug in the extension on Linux specifically.

I've created a branch and a [draft PR](https://github.com/cytechmobile/radicle-vscode-extension/pull/173) with [a minimal test](https://github.com/cytechmobile/radicle-vscode-extension/pull/173/files#diff-7827ab362656b2d306fce0afb1595d9fbd9d3b42aa8064a546002311ac6fdf5c) to illustrate this. (Check the result of [the ubuntu job](https://github.com/cytechmobile/radicle-vscode-extension/actions/runs/12973740647/job/36182785943?pr=173))

However since I'm not on Linux, I can't reproduce it locally, and I'd like to confirm with you before creating a bug. Could you help reproduce this?

As far a I can tell, based on `e2e-testing.yaml`, the steps to reproduce this are:
1. before installing Radicle, set `RAD_HOME` to non-default path
2. install radicle
3. create a new radicle identity (`rad auth`)
4. start VSCode
5. open the Radicle channel in the Output Panel

The radicle identity should be picked up correctly, but according to my testing it is not.

2025-01-26 10:45 UTC, QZera commented on test/e2e/wdio.conf.ts
> +  ],
Updated as suggested!

2025-01-29 19:03 UTC, maninak commented on test/e2e/specs/settings.spec.ts
> +      )
Wow..

OK, if you think it would not be worse having our own function that types in the setting id in the setting search/filter input then let's do it.

Up to you. I'm resolving beforehand.

2025-01-29 19:06 UTC, maninak commented on test/e2e/wdio.conf.ts
> +  waitforTimeout: 20000,
I'm not a huge fan of this. If there are specific things we need to wait for that take a long time we should increase it per case IMO.

Anyway, given our current constraints I'm resolving this.

2025-01-29 19:46 UTC, maninak commented on test/e2e/specs/settings.spec.ts
> +  describe('VS Code, when updating the "Path to Radicle to Node Home" setting, @skipLinuxCI', () => {
It looks like for the tests we're creating a [non-password protected Radicle identity](https://github.com/cytechmobile/radicle-vscode-extension/pull/167/files#diff-5cc2e1ccca06682f297520ead2dd9b3ef2bdc286aa52ae224b545f458b0a978cR52).

Yet in the test you shared we're (falsely!) expecting to read [""](https://github.com/cytechmobile/radicle-vscode-extension/pull/173/files#diff-7827ab362656b2d306fce0afb1595d9fbd9d3b42aa8064a546002311ac6fdf5cR29) in the Radicle Output channel. In this case the expected output is ["Using non-password-protected Radicle identity"](https://github.com/cytechmobile/radicle-vscode-extension/blob/feat/settings-e2e-tests/src/ux/radicleIdentityAuth.ts#L26-L27).

In fact it would be better that all our tests use a password-protected identity by default to better simulate real-world scenarios. There's also good argument to cover with tests some basic functionality (similar to what you've done in your testing PR above, actually) to ensure we haven't broken support for non-password-protected identities (has happened to me in the past..).

2025-02-02 20:33 UTC, QZera reviewed
Didn't have enough time to properly resolve the "skip linux CI" comment 😞. That said, I believe this PR still provides enough value to be merged as is.

Feel free to make any tweaks/changes to this as you see fit. I'll be available if you have any questions I can help with.

2025-02-02 20:33 UTC, QZera commented on test/e2e/specs/settings.spec.ts
> +  describe('VS Code, when updating the "Path to Radicle to Node Home" setting, @skipLinuxCI', () => {
Oh, I didn't know the extension had different messages for this. Still, knowing this, the output of the tests doesn't make sense.

On macOS we get "already unsealed":
```
[10:22:19 INFO ] Extension Radicle v0.6.0 activated
[10:22:19 INFO ] Using Radicle CLI v1.1.0 from "/Users/runner/work/radicle-vscode-extension/radicle-vscode-extension/.radicle/bin/rad"
[10:22:20 INFO ] Using already unsealed Radicle identity did:key:z6MkhF2Wyt9VmDivFvgSZFkbMgVpE6Y63ZPg5X6frkiFxWXX
[10:22:20 ERROR] [GET] "http://127.0.0.1:8080/api/v1": <no response> fetch failed
```

On linux we get "non-authenticated identity":
```
[10:22:25 INFO ] Extension Radicle v0.6.0 activated
[10:22:25 INFO ] Using Radicle CLI v1.1.0 from "/home/runner/work/radicle-vscode-extension/radicle-vscode-extension/.radicle/bin/rad"
[10:22:25 WARN ] Found non-authenticated identity did:key:z6Mkf8P6HefuUcM7gp3o55Ntu95hUhQrSLpbtyEuZwLekAQu stored in "/home/runner/.radicle"
[10:22:25 ERROR] [GET] "http://127.0.0.1:8080/api/v1": <no response> fetch failed
[10:22:33 WARN ] Found non-authenticated identity did:key:z6Mkf8P6HefuUcM7gp3o55Ntu95hUhQrSLpbtyEuZwLekAQu stored in "/home/runner/work/radicle-vscode-extension/radicle-vscode-extension/.radicle"
```

Both of which aren't the expected "Using non-password-protected Radicle identity"

---

I spent some more time trying to debug this, but unfortunately, had no luck. I also didn't have much time left to look into non-password protected and protected identities.

I've updated the comment to a TODO, to indicate there's still work left to do on this.

2025-02-02 20:33 UTC, QZera commented on test/e2e/specs/settings.spec.ts
> +      )
I hear you, and I thought about it, there's a couple of reasons I opted not to make a new function for this.

1. Size/complexity: if I was to make a function it would essentially be the same implementation as the wdio one with the difference being what's filled in the searchbox. And since `findSetting` is pretty large, that made me apprehensive.

2. The reason I chose wdio in the first place, was due to the fact it had methods for performing actions like these  , rather than having to implement them from scratch. Which I thought was a good fit given our time constraints. So, re-implementing this function kind of feels like going against that philosophy.

Now, given how much I've had to delve into wdio-vscode-service's source code 😩, this might be misguided. But given the current situation, I'm leaving this as is.

2026-06-18 09:13 UTC, maninak commented
Closing in favor of #178. The merge conflicts due to the augmented testing infra and all other maintenance changes, make it impossible to resolve the endless merge.

2026-06-18 09:13 UTC, closed without merging